"""Scout Board seed loader.

Reads data/prospects.csv (the 27 curated research picks, ids 500+) and emits
supabase_scout_data.sql — INSERTs for event_prospects. Lance runs the generated SQL in the
Supabase SQL editor AFTER supabase_scout_schema.sql (same flow as the vending load).

Rules (per docs/superpowers/specs/2026-07-13-scout-board-design.md):
  - EXCLUDE the known no-gos: food_truck_friendly == 'excluded' OR verification_status == 'excluded'
    (Double X, Lucas Oil, Serenity Valley, Air Show) -> Trint's board is "respectable events only".
  - drive_time_min = round(distance_mi / 50 * 60)  (rough triage estimate, not routing).
  - food_policy: explicit_yes / concession_friendly -> 'open'; else -> 'unknown'.
  - stage = 'researching' for every seed row (Lance's prescreen backlog; only 'ready' reaches Trint).
  - INSERT ... ON CONFLICT (id) DO NOTHING  -> re-running never clobbers Lance's in-app edits.
  - After the inserts, bump the identity sequence above the seed ids so desk-added leads
    (which auto-assign ids) never collide with the 500-range seed.

Usage:  python scout_seed_gen_sql.py     (writes supabase_scout_data.sql next to this script)
"""
import csv
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "data", "prospects.csv")
OUT = os.path.join(HERE, "supabase_scout_data.sql")

# event_prospects columns we populate at seed (the rest use table defaults / Lance fills later).
COLS = [
    "id", "source", "stage", "name", "event_type", "city", "state", "county",
    "distance_mi", "drive_time_min", "date_text", "month", "crowd_text", "crowd_estimate",
    "fee_text", "application_method", "food_policy", "notes", "source_url", "lat", "lng",
]


def s(v):
    """Quote a text value for SQL, or NULL if empty."""
    v = (v or "").strip()
    if not v:
        return "NULL"
    return "'" + v.replace("'", "''") + "'"


def i(v):
    """Integer literal or NULL."""
    v = (v or "").strip()
    if not v:
        return "NULL"
    try:
        return str(int(float(v)))
    except ValueError:
        return "NULL"


def f(v):
    """Float literal or NULL."""
    v = (v or "").strip()
    if not v:
        return "NULL"
    try:
        return repr(float(v))
    except ValueError:
        return "NULL"


def drive_time(distance):
    d = (distance or "").strip()
    if not d:
        return "NULL"
    try:
        return str(round(float(d) / 50.0 * 60))
    except ValueError:
        return "NULL"


def food_policy(friendly):
    return "open" if (friendly or "").strip() in ("explicit_yes", "concession_friendly") else "unknown"


def main():
    rows = list(csv.DictReader(open(SRC, encoding="utf-8-sig")))
    kept, excluded = [], []
    for r in rows:
        if r.get("food_truck_friendly", "").strip() == "excluded" or \
           r.get("verification_status", "").strip() == "excluded":
            excluded.append(r)
            continue
        kept.append(r)

    lines = [
        "-- The Glizzness — Scout Board seed data (generated by scout_seed_gen_sql.py).",
        "-- Run AFTER supabase_scout_schema.sql, in the Supabase SQL editor.",
        "-- ON CONFLICT DO NOTHING: safe to re-run; never overwrites Lance's in-app edits.",
        "",
        "begin;",
        "",
        f"insert into event_prospects ({', '.join(COLS)}) values",
    ]

    values = []
    for r in kept:
        src_url = r.get("homepage_url") or r.get("primary_source_url")
        vals = [
            i(r.get("id")),
            "'research'",
            "'researching'",
            s(r.get("name")),
            s(r.get("event_type")),
            s(r.get("city")),
            s(r.get("state")),
            s(r.get("county")),
            i(r.get("distance_from_columbia_mi")),
            drive_time(r.get("distance_from_columbia_mi")),
            s(r.get("typical_dates")),
            i(r.get("month")),
            s(r.get("attendance_text")),
            i(r.get("attendance_estimate")),
            s(r.get("food_vendor_fee")),
            s(r.get("application_method")),
            "'" + food_policy(r.get("food_truck_friendly")) + "'",
            s(r.get("notes")),
            s(src_url),
            f(r.get("lat")),
            f(r.get("lng")),
        ]
        values.append("  (" + ", ".join(vals) + ")")

    lines.append(",\n".join(values) + "\non conflict (id) do nothing;")
    lines += [
        "",
        "-- Bump the identity sequence above the seeded ids so desk-added (inbound) leads",
        "-- auto-assign fresh, non-colliding ids.",
        "select setval(pg_get_serial_sequence('event_prospects', 'id'),",
        "              (select max(id) from event_prospects));",
        "",
        "commit;",
        "",
    ]

    with open(OUT, "w", encoding="utf-8", newline="\n") as out:
        out.write("\n".join(lines))

    print("Scout seed generated.")
    print("  source rows : {}".format(len(rows)))
    print("  excluded    : {}  ({})".format(
        len(excluded), ", ".join(r.get("name", "?") for r in excluded)))
    print("  seeded      : {}".format(len(kept)))
    print("  -> wrote    : {}".format(OUT))
    print("Next: paste supabase_scout_data.sql into the Supabase SQL editor (after the schema).")


if __name__ == "__main__":
    main()
