-- Vending Circuit — Supabase (Postgres) schema  [Phase 4]
-- Mirrors DATA_MODEL.md. Safe to run in the EXISTING Glizzness Supabase project
-- (table names are vending-prefixed; no collision with the accounting tables).
-- Idempotent-ish: drops the vending objects first, then recreates.

begin;

drop view  if exists vending_published_events cascade;
drop table if exists vending_fees           cascade;
drop table if exists vending_sources        cascade;
drop table if exists vending_event_schedules cascade;
drop table if exists vending_events         cascade;
drop table if exists vending_markets        cascade;

-- ---- markets (top-tier map hubs) ----
create table vending_markets (
  id          int primary key,
  name        text not null,
  anchor_city text not null,
  state       text not null,
  center_lat  double precision,
  center_lng  double precision,
  default_zoom int default 9,
  distance_from_columbia_mi int,
  summary     text
);

-- ---- events ----
create table vending_events (
  id                int primary key,
  market_id         int references vending_markets(id),
  name              text not null,
  city              text,
  state             text,
  county            text,          -- county/parish; powers the map's county filter (esp. Missouri)
  event_type        text check (event_type in
      ('state_fair','county_fair','festival','food_truck_rally','farmers_market',
       'oktoberfest','craft_fair','art_fair','music_fest','bbq_fest','balloon_fest',
       'holiday_market','cultural_fest','venue','booking_platform')),
  cadence           text check (cadence in
      ('annual','multi_week','monthly','weekly','recurring','year_round')),
  is_recurring_venue   boolean default false,
  food_truck_friendly  text check (food_truck_friendly in
      ('explicit_yes','concession_friendly','unconfirmed','excluded')),
  trip_type         text check (trip_type in ('hometown','day_trip','overnight')),
  verification_status text check (verification_status in
      ('verified','partial','defunct','excluded')),
  needs_confirmation boolean default false,
  distance_from_columbia_mi int,
  month             text,          -- convenience; normalized dates live in vending_event_schedules
  typical_dates     text,          -- verbatim display string
  attendance_estimate int,
  attendance_text   text,
  food_vendor_fee   text,
  application_method text,
  contact_name      text,
  contact_email     text,
  contact_phone     text,
  homepage_url      text,          -- drives the conditional UI link
  primary_source_url text,
  lat               double precision,
  lng               double precision,
  notes             text,
  last_verified     date            -- when this row was last research-verified (powers freshness_report.py)
);
create index vending_events_market_idx on vending_events(market_id);
create index vending_events_trip_idx   on vending_events(trip_type);
create index vending_events_month_idx  on vending_events(month);
create index vending_events_county_idx on vending_events(county);

-- ---- schedules (1 event -> many) ----
create table vending_event_schedules (
  id              int primary key,
  event_id        int references vending_events(id) on delete cascade,
  month           int,
  start_date      date,
  end_date        date,
  recurrence_text text,
  display_text    text,
  year_specific   boolean default false
);
create index vending_sched_event_idx on vending_event_schedules(event_id);

-- ---- sources (provenance) ----
create table vending_sources (
  id        int generated by default as identity primary key,
  event_id  int references vending_events(id) on delete cascade,
  url       text,
  quality   text
);

-- ---- fees (STUBBED — defined, populated later) ----
create table vending_fees (
  id        int generated by default as identity primary key,
  event_id  int references vending_events(id) on delete cascade,
  fee_type  text,
  amount    numeric,
  unit      text,
  notes     text
);

-- ---- published view = the validation gate ----
-- Only verified/partial, food-truck-viable, fully-located events surface to the UI.
create view vending_published_events as
select e.*, m.name as market_name, m.anchor_city, m.center_lat as market_lat, m.center_lng as market_lng
from vending_events e
join vending_markets m on m.id = e.market_id
where e.verification_status in ('verified','partial')
  and e.food_truck_friendly <> 'excluded'
  and e.lat is not null and e.lng is not null;

-- ---- RLS: public read-only (matches project pattern; service_role bypasses) ----
alter table vending_markets          enable row level security;
alter table vending_events           enable row level security;
alter table vending_event_schedules  enable row level security;
alter table vending_sources          enable row level security;
alter table vending_fees             enable row level security;

create policy vending_markets_read   on vending_markets          for select using (true);
create policy vending_events_read    on vending_events           for select using (true);
create policy vending_sched_read     on vending_event_schedules  for select using (true);
create policy vending_sources_read   on vending_sources          for select using (true);
create policy vending_fees_read      on vending_fees             for select using (true);

-- the gate view is the canonical public "published" endpoint; let anon read it
grant select on vending_published_events to anon, authenticated;

commit;

-- ============================================================
-- LOAD (after the schema above is created):
-- Option A — Supabase dashboard: Table editor -> each table -> Import CSV from
--   data/markets.csv, data/events.csv, data/event_schedules.csv (empty cells = NULL).
-- Option B — psql \copy (run locally with the service connection string):
--   \copy vending_markets          from 'data/markets.csv'          csv header
--   \copy vending_events           from 'data/events.csv'           csv header
--   \copy vending_event_schedules  from 'data/event_schedules.csv'  csv header
-- Load order matters (FKs): markets -> events -> event_schedules.
-- ============================================================

-- VALIDATION (run after load; all should return sensible numbers):
-- select count(*) from vending_markets;                       -- expect 31
-- select count(*) from vending_events;                        -- expect 301
-- select count(*) from vending_event_schedules;               -- expect 301
-- select count(*) from vending_events where market_id is null;-- expect 0
-- select count(*) from vending_events where lat is null;      -- expect 0
-- select count(*) from vending_published_events;              -- expect 298 (301 minus 1 defunct + 2 excluded)
