-- The Glizzness — Scout Board schema (Supabase / Postgres)
-- Run ONCE in the Supabase SQL editor. Safe alongside the accounting + vending_* +
-- catering + cart_schedule tables.
--
-- SECURITY MODEL (differs from the public tables on purpose):
--   These three tables are PRIVATE. RLS is ON and the ONLY policies grant access to the
--   `authenticated` role — there is NO `anon` policy. So the public anon key baked into the
--   website (assets/config.js) can read/write NOTHING here. The gated pages (hub/, scout/,
--   hub/desk) log a user in with Supabase Auth; supabase-js then sends that user's JWT
--   (role = authenticated) on every call, which the policies below allow. The login gate is
--   the real wall — the database itself refuses anonymous access.
--
-- Auth users (Trint + Lance) are created by hand in the Supabase dashboard
-- (Authentication -> Users -> Add user). There is NO public sign-up. See SCOUT_BOARD.md.

begin;

-- ---------------------------------------------------------------------------
-- 1. event_prospects — one row per vending opportunity (seed picks + inbound leads)
-- ---------------------------------------------------------------------------
create table if not exists event_prospects (
  id                  bigint generated by default as identity primary key,  -- seed keeps 500+; desk leads auto-assign
  source              text not null default 'research'
                        check (source in ('research','inbound')),
  stage               text not null default 'researching'
                        check (stage in ('researching','ready')),           -- Trint's board shows only 'ready'
  research_note       text,                       -- Claude's CLI findings/sources, for Lance
  name                text not null,
  event_type          text,
  city                text,
  state               text,
  county              text,
  distance_mi         int,
  drive_time_min      int,                         -- computed at seed: round(distance_mi / 50 * 60)
  date_text           text,                        -- human dates, e.g. "Weekly race nights"
  month               int,
  crowd_text          text,
  crowd_estimate      int,
  suggested_crew      text,                        -- e.g. "2–3" — estimate now, staffing model fills later
  fee_text            text,                        -- vendor fee; blank -> UI shows "not yet known"
  application_method  text,
  application_deadline text,                        -- not in seed source -> Lance fills from the desk
  food_policy         text default 'unknown'
                        check (food_policy in ('open','competing','unknown')),
  notes               text,
  source_url          text,
  lat                 double precision,
  lng                 double precision,
  booked              boolean not null default false,
  booked_at           timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create index if not exists event_prospects_stage_idx  on event_prospects(stage);
create index if not exists event_prospects_booked_idx on event_prospects(booked);

-- ---------------------------------------------------------------------------
-- 2. prospect_decisions — Trint's current call (one per prospect, upserted on re-tap)
-- ---------------------------------------------------------------------------
create table if not exists prospect_decisions (
  id           bigint generated always as identity primary key,
  prospect_id  bigint not null unique references event_prospects(id) on delete cascade,
  decision     text not null check (decision in ('yes','maybe','no')),
  decided_by   text,                               -- the logged-in user's email
  decided_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 3. prospect_thread — the Q&A between Trint and Lance (grows; rendered newest-last)
-- ---------------------------------------------------------------------------
create table if not exists prospect_thread (
  id           bigint generated always as identity primary key,
  prospect_id  bigint not null references event_prospects(id) on delete cascade,
  author       text not null,                      -- 'trint' / 'lance' (or the email)
  body         text not null,
  created_at   timestamptz not null default now()
);
create index if not exists prospect_thread_prospect_idx on prospect_thread(prospect_id, created_at);

-- ---------------------------------------------------------------------------
-- RLS — authenticated-only. No anon policy anywhere = the public key is locked out.
-- ---------------------------------------------------------------------------
alter table event_prospects    enable row level security;
alter table prospect_decisions enable row level security;
alter table prospect_thread    enable row level security;

-- Both trusted users (Trint + Lance) can do everything once logged in.
grant select, insert, update, delete on event_prospects,    prospect_decisions, prospect_thread to authenticated;

create policy event_prospects_all on event_prospects
  for all to authenticated using (true) with check (true);
create policy prospect_decisions_all on prospect_decisions
  for all to authenticated using (true) with check (true);
create policy prospect_thread_all on prospect_thread
  for all to authenticated using (true) with check (true);

-- NOTE: intentionally NO grant/policy for `anon`. Logged-out = zero access.
-- service_role (dashboard/automation) bypasses RLS for maintenance as usual.

commit;

-- Peek (run as service_role in the SQL editor):
--   select id, stage, name, city, distance_mi, fee_text, booked from event_prospects order by id;
--   select d.decision, p.name from prospect_decisions d join event_prospects p on p.id = d.prospect_id;
