"""Generate supabase_vending_data.sql (INSERTs) from data/*.csv.
Run after vending_circuit_etl.py + vending_circuit_geocode.py.
Load order in the output: markets -> events -> schedules (FK-safe).
"""
import csv

INT = {"id","market_id","default_zoom","distance_from_columbia_mi","attendance_estimate","month","event_id"}
FLOAT = {"center_lat","center_lng","lat","lng"}
BOOL = {"is_recurring_venue","needs_confirmation","year_specific"}

def val(col, v):
    v = (v or "").strip()
    if v == "":
        return "NULL"
    if col in INT:
        try: return str(int(v))
        except ValueError: return "NULL"
    if col in FLOAT:
        try: return str(float(v))
        except ValueError: return "NULL"
    if col in BOOL:
        return "true" if v.lower() in ("true","1","yes") else "false"
    return "'" + v.replace("'", "''") + "'"

def emit(table, path, out):
    rows = list(csv.DictReader(open(path, encoding="utf-8")))
    cols = list(rows[0].keys())
    out.append(f"-- {table}: {len(rows)} rows")
    for r in rows:
        out.append(f"insert into {table} ({', '.join(cols)}) values ({', '.join(val(c, r[c]) for c in cols)});")
    out.append("")
    return len(rows)

out = ["-- Vending Circuit data load (generated by vending_circuit_gen_sql.py).",
       "-- Run AFTER supabase_vending_schema.sql.", "begin;", ""]
nm = emit("vending_markets", "data/markets.csv", out)
ne = emit("vending_events", "data/events.csv", out)
ns = emit("vending_event_schedules", "data/event_schedules.csv", out)
out += ["commit;", "",
        f"-- checks: markets {nm} | events {ne} | schedules {ns} | published expect 124",
        "-- select count(*) from vending_published_events;", ""]
open("supabase_vending_data.sql","w",encoding="utf-8").write("\n".join(out))
print(f"wrote supabase_vending_data.sql (markets {nm}, events {ne}, schedules {ns})")
