"""Generate supabase_vending_data.sql (INSERTs) from data/*.csv.
Run after vending_circuit_etl.py + vending_circuit_geocode.py.
Load order in the output: markets -> events -> schedules (FK-safe).
"""
import csv, os

INT = {"id","market_id","default_zoom","distance_from_columbia_mi","attendance_estimate","month","event_id"}
FLOAT = {"center_lat","center_lng","lat","lng"}
BOOL = {"is_recurring_venue","needs_confirmation","year_specific"}

def val(col, v):
    v = (v or "").strip()
    if v == "":
        return "NULL"
    if col in INT:
        try: return str(int(v))
        except ValueError: return "NULL"
    if col in FLOAT:
        try: return str(float(v))
        except ValueError: return "NULL"
    if col in BOOL:
        return "true" if v.lower() in ("true","1","yes") else "false"
    return "'" + v.replace("'", "''") + "'"

def emit(table, path, out):
    if not os.path.exists(path):
        return 0
    rows = list(csv.DictReader(open(path, encoding="utf-8")))
    if not rows:
        return 0
    cols = list(rows[0].keys())
    out.append(f"-- {table}: {len(rows)} rows")
    for r in rows:
        out.append(f"insert into {table} ({', '.join(cols)}) values ({', '.join(val(c, r[c]) for c in cols)});")
    out.append("")
    return len(rows)

out = ["-- Vending Circuit data load (generated by vending_circuit_gen_sql.py).",
       "-- Run AFTER supabase_vending_schema.sql. IDEMPOTENT: truncate-then-insert, so re-run",
       "-- anytime to refresh (handles added/removed events; no PK conflicts, no hand-patching).",
       "begin;",
       "truncate vending_markets, vending_events, vending_event_schedules, vending_sources, vending_fees restart identity cascade;",
       ""]
nm = emit("vending_markets", "data/markets.csv", out)
ne = emit("vending_events", "data/events.csv", out)
# The 7-run research "prospects" (data/prospects.csv, ids 500+) are NO LONGER loaded into the public
# Midwest Event Finder — they're Trint's private picks and will feed the Scout board's own table
# (event_prospects). Kept on disk for that future ETL. Re-run this + the SQL to purge any that were
# loaded earlier. (The finder's app.js also filters ids >= 500 out client-side as a belt-and-suspenders.)
ns = emit("vending_event_schedules", "data/event_schedules.csv", out)
out += ["commit;", "",
        f"-- checks: markets {nm} | events {ne} | schedules {ns} | published = verified/partial, non-excluded, geocoded",
        "-- select count(*) from vending_published_events;", ""]
open("supabase_vending_data.sql","w",encoding="utf-8").write("\n".join(out))
print(f"wrote supabase_vending_data.sql (markets {nm}, events {ne}, schedules {ns})")
